################################################################################
#
# dashboard-pi-wpewebkit
#
################################################################################

DASHBOARD_PI_WPEWEBKIT_VERSION = 2.52.5
DASHBOARD_PI_WPEWEBKIT_SITE = https://wpewebkit.org/releases
DASHBOARD_PI_WPEWEBKIT_SOURCE = wpewebkit-$(DASHBOARD_PI_WPEWEBKIT_VERSION).tar.xz
DASHBOARD_PI_WPEWEBKIT_INSTALL_STAGING = YES
DASHBOARD_PI_WPEWEBKIT_LICENSE = LGPL-2.1+, BSD-2-Clause
DASHBOARD_PI_WPEWEBKIT_LICENSE_FILES = \
	Source/WebCore/LICENSE-APPLE \
	Source/WebCore/LICENSE-LGPL-2.1
DASHBOARD_PI_WPEWEBKIT_CPE_ID_VENDOR = wpewebkit
DASHBOARD_PI_WPEWEBKIT_CPE_ID_PRODUCT = wpe_webkit
DASHBOARD_PI_WPEWEBKIT_DEPENDENCIES = \
	host-gperf host-python3 host-ruby host-unifdef \
	fontconfig freetype harfbuzz icu jpeg libepoxy libgcrypt libgles \
	libinput libpng libsoup3 libtasn1 libdrm libgbm libxkbcommon libxslt \
	systemd webp

DASHBOARD_PI_WPEWEBKIT_CMAKE_BACKEND = ninja
DASHBOARD_PI_WPEWEBKIT_CONF_ENV = WK_USE_CCACHE=NO

DASHBOARD_PI_WPEWEBKIT_CONF_OPTS = \
	-DPORT=WPE \
	-DENABLE_API_TESTS=OFF \
	-DENABLE_BUBBLEWRAP_SANDBOX=OFF \
	-DENABLE_DOCUMENTATION=OFF \
	-DENABLE_INTROSPECTION=OFF \
	-DENABLE_JOURNALD_LOG=ON \
	-DENABLE_MINIBROWSER=OFF \
	-DENABLE_VIDEO=OFF \
	-DENABLE_WEB_AUDIO=OFF \
	-DENABLE_WEB_CODECS=OFF \
	-DENABLE_WEB_RTC=OFF \
	-DENABLE_WPE_1_1_API=OFF \
	-DENABLE_WPE_LEGACY_API=OFF \
	-DENABLE_WPE_PLATFORM=ON \
	-DENABLE_WPE_PLATFORM_DRM=ON \
	-DENABLE_WPE_PLATFORM_HEADLESS=ON \
	-DENABLE_WPE_PLATFORM_WAYLAND=OFF \
	-DENABLE_WPE_QT_API=OFF \
	-DUSE_ATK=OFF \
	-DUSE_AVIF=OFF \
	-DUSE_FLITE=OFF \
	-DUSE_GBM=ON \
	-DUSE_GSTREAMER_GL=OFF \
	-DUSE_JPEGXL=OFF \
	-DUSE_LCMS=OFF \
	-DUSE_LIBBACKTRACE=OFF \
	-DUSE_LIBDRM=ON \
	-DUSE_SKIA=ON \
	-DUSE_SYSPROF_CAPTURE=OFF \
	-DUSE_WOFF2=OFF

$(eval $(cmake-package))
