################################################################################
#
# dashboard-pi-wpewebkit
#
################################################################################

DASHBOARD_PI_WPEWEBKIT_VERSION = 2.52.5
DASHBOARD_PI_WPEWEBKIT_SITE = https://wpewebkit.org/releases
DASHBOARD_PI_WPEWEBKIT_SOURCE = wpewebkit-$(DASHBOARD_PI_WPEWEBKIT_VERSION).tar.xz
DASHBOARD_PI_WPEWEBKIT_INSTALL_STAGING = YES
DASHBOARD_PI_WPEWEBKIT_LICENSE = LGPL-2.1+, BSD-2-Clause
DASHBOARD_PI_WPEWEBKIT_LICENSE_FILES = \
	Source/WebCore/LICENSE-APPLE \
	Source/WebCore/LICENSE-LGPL-2.1
DASHBOARD_PI_WPEWEBKIT_CPE_ID_VENDOR = wpewebkit
DASHBOARD_PI_WPEWEBKIT_CPE_ID_PRODUCT = wpe_webkit
DASHBOARD_PI_WPEWEBKIT_DEPENDENCIES = \
	host-gperf host-python3 host-ruby host-unifdef \
	fontconfig freetype harfbuzz icu jpeg libepoxy libgcrypt libgles \
	libinput libpng libsoup3 libtasn1 libdrm libgbm libxkbcommon libxslt \
	gstreamer1 gst1-libav gst1-plugins-bad gst1-plugins-base \
	gst1-plugins-good systemd webp

DASHBOARD_PI_WPEWEBKIT_CMAKE_BACKEND = ninja
DASHBOARD_PI_WPEWEBKIT_CONF_ENV = WK_USE_CCACHE=NO

DASHBOARD_PI_WPEWEBKIT_CONF_OPTS = \
	-DPORT=WPE \
	-DENABLE_API_TESTS=OFF \
	-DENABLE_BUBBLEWRAP_SANDBOX=OFF \
	-DENABLE_DOCUMENTATION=OFF \
	-DENABLE_GAMEPAD=OFF \
	-DENABLE_INTROSPECTION=OFF \
	-DENABLE_JOURNALD_LOG=ON \
	-DENABLE_MINIBROWSER=OFF \
	-DENABLE_PDFJS=OFF \
	-DENABLE_SPEECH_SYNTHESIS=OFF \
	-DENABLE_THUNDER=OFF \
	-DENABLE_WEBDRIVER=OFF \
	-DENABLE_WEBINSPECTORUI=OFF \
	-DENABLE_MEDIA_SOURCE=ON \
	-DENABLE_VIDEO=ON \
	-DENABLE_WEB_AUDIO=ON \
	-DENABLE_WEB_CODECS=ON \
	-DENABLE_WEB_RTC=OFF \
	-DENABLE_WK_WEB_EXTENSIONS=OFF \
	-DENABLE_WPE_1_1_API=OFF \
	-DENABLE_WPE_LEGACY_API=OFF \
	-DENABLE_WPE_PLATFORM=ON \
	-DENABLE_WPE_PLATFORM_DRM=ON \
	-DENABLE_WPE_PLATFORM_HEADLESS=OFF \
	-DENABLE_WPE_PLATFORM_WAYLAND=OFF \
	-DENABLE_WPE_QT_API=OFF \
	-DUSE_ATK=OFF \
	-DUSE_AVIF=OFF \
	-DUSE_FLITE=OFF \
	-DUSE_GBM=ON \
	-DUSE_GSTREAMER=ON \
	-DUSE_GSTREAMER_GL=ON \
	-DUSE_JPEGXL=OFF \
	-DUSE_LCMS=OFF \
	-DUSE_LIBBACKTRACE=OFF \
	-DUSE_LIBHYPHEN=OFF \
	-DUSE_LIBDRM=ON \
	-DUSE_SKIA=ON \
	-DUSE_SPIEL=OFF \
	-DUSE_SYSPROF_CAPTURE=OFF \
	-DUSE_WOFF2=OFF

ifeq ($(BR2_CCACHE),y)
DASHBOARD_PI_WPEWEBKIT_CONF_OPTS += \
	-DCMAKE_C_COMPILER_LAUNCHER=$(HOST_DIR)/bin/ccache \
	-DCMAKE_CXX_COMPILER_LAUNCHER=$(HOST_DIR)/bin/ccache
endif

$(eval $(cmake-package))
